version: '3.8'

services:
  dbpogo:
    image: postgres:13.22
    environment:
      - TZ=America/Guayaquil
      - POSTGRES_DB=pogo
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    networks:
      - desarrollo_net
  #Servicio pa PGADMIN4
  pgpogo:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=pme.pogo@yavirac.edu.ec
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    volumes:
      - pg_admin4:/var/lib/pgadmin
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.pgpogo.entrypoints=http"
        - "traefik.http.routers.pgpogo.rule=Host(`pgpogo.byronrm.com`)"
        - "traefik.http.middlewares.pgpogo-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.pgpogo.middlewares=pgpogo-https-redirect"
        - "traefik.http.routers.pgpogo-secure.entrypoints=https"
        - "traefik.http.routers.pgpogo-secure.rule=Host(`pgpogo.byronrm.com`)"
        - "traefik.http.routers.pgpogo-secure.tls=true"
        - "traefik.http.routers.pgpogo-secure.tls.certresolver=http"
        - "traefik.http.routers.pgpogo-secure.service=pgpogo"
        - "traefik.http.services.pgpogo.loadbalancer.server.port=80"
        - "traefik.docker.network=traefik-public"
    networks:
      - desarrollo_net
      - traefik-public
volumes:
  pg_data:
    external: true
  pg_admin4:
    external: true
networks:
  desarrollo_net:
    external: true
  traefik-public:
    external: true