version: "3.8"

services:
  pgmoreno:
    image: pgpogo:latest
    build: .
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.pgpogo.entrypoints=http"
        - "traefik.http.routers.pgpogo.rule=Host(`pgpogo.byronrm.com`)"
        - "traefik.http.middlewares.pgpogo-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.pgpogo.middlewares=pgpogo-https-redirect"
        - "traefik.http.routers.pgpogo-secure.entrypoints=https"
        - "traefik.http.routers.pgpogo-secure.rule=Host(`pgpogo.byronrm.com`)"
        - "traefik.http.routers.pgpogo-secure.tls=true"
        - "traefik.http.routers.pgpogo-secure.tls.certresolver=http"
        - "traefik.http.routers.pgpogo-secure.service=pgpogo"
        - "traefik.http.services.pgpogo.loadbalancer.server.port=80"
        - "traefik.docker.network=traefik-public"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true